// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Context;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(DefaultDbContext))]
    partial class DefaultDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WebApi.Entities.BallTbl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("FkColorId")
                        .HasColumnType("int");

                    b.Property<int>("FkModelId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("FkColorId");

                    b.HasIndex("FkModelId");

                    b.ToTable("BallTbls");
                });

            modelBuilder.Entity("WebApi.Entities.ColorTbl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.ToTable("ColorTbls");
                });

            modelBuilder.Entity("WebApi.Entities.ModelTbl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.ToTable("ModelTbls");
                });

            modelBuilder.Entity("WebApi.Entities.UserTbl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("UserTbls");
                });

            modelBuilder.Entity("WebApi.Entities.BallTbl", b =>
                {
                    b.HasOne("WebApi.Entities.ColorTbl", "ColorTbl")
                        .WithMany("BallTbls")
                        .HasForeignKey("FkColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Entities.ModelTbl", "ModelTbl")
                        .WithMany("BallTbls")
                        .HasForeignKey("FkModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ColorTbl");

                    b.Navigation("ModelTbl");
                });

            modelBuilder.Entity("WebApi.Entities.ColorTbl", b =>
                {
                    b.Navigation("BallTbls");
                });

            modelBuilder.Entity("WebApi.Entities.ModelTbl", b =>
                {
                    b.Navigation("BallTbls");
                });
#pragma warning restore 612, 618
        }
    }
}
